### ISSUE TITLE
Cancel button Hide

### ISSUE THREAD

**Issue by ErAshu** [popodidi/HTagView#11]
How to hide Cancel button? In your sample, tagView1 is showing 1 cancel button and tagView2 showing 4 cancel button.
How can i manage this? I have to show in one view without cancel button but second view should all tag have cancel button. 

![image](https://user-images.githubusercontent.com/4178384/31320631-6f94e392-ac95-11e7-82c1-a599d7fb1fc5.png)

Please guide.
Thanks

**Comment by popodidi** [comment]
In you `HTagViewDataSource` implementation, you could specify tag type for each tag.
In `func tagView(_ tagView: HTagView, tagTypeAtIndex index: Int) -> HTagType`, specifying for each `index` instead of simply returning `.cancel` will do the trick.
