### ISSUE TITLE
Disable selection once limit has been reached

### ISSUE THREAD

**Issue by mteera** [popodidi/HTagView#13]
How do I disable the selection of a tag once it has reached a limit?

    var selectedInterests = [Int]()

    func tagView(_ tagView: HTagView, tagSelectionDidChange selectedIndices: [Int]) {
        selectedInterests.removeAll()

        for i in selectedIndices {
            selectedInterests.append(i)
            
            if selectedInterests.count > 3 {
                print("limit reached")
            }
        }
    }

**Comment by popodidi** [comment]
try this
```
tagView.selectTagAtIndex(index)
tagView.deselectTagAtIndex(index)
```
