### ISSUE TITLE
Add shadow to tags?

### ISSUE THREAD

**Issue by NirajCapermint** [popodidi/HTagView#17]
I almost use this library in my every projects. Now I need to give to shadow to all the tags I tried in your library but got no luck. Here is screenshot pf actually what I want.

![Screenshot 2019-03-19 at 7 05 00 PM](https://user-images.githubusercontent.com/41157695/54609923-eaa9b700-4a79-11e9-8a4b-e8bb1da2df87.png)

**Comment by steveGates890** [comment]
> I almost use this library in my every projects. Now I need to give to shadow to all the tags I tried in your library but got no luck. Here is screenshot pf actually what I want.
> 
> ![Screenshot 2019-03-19 at 7 05 00 PM](https://user-images.githubusercontent.com/41157695/54609923-eaa9b700-4a79-11e9-8a4b-e8bb1da2df87.png)

I think actually developer of this pod don't know about his own pods, otherwise they sure to reply.

**Comment by popodidi** [comment]
please try out the new feature of version `4.1`
```
tagView.tagElevation = 40
```
