### ISSUE TITLE
Two line tag

### ISSUE THREAD

**Issue by narayana-wijaya** [popodidi/HTagView#5]
How to set two line text if tag text is too long? For now it is cut at the end. I want it to wrap by word in the end of tag. I change in htagview tag but it is not working. Thanks

<img width="372" alt="screen shot 2017-02-07 at 11 10 45 am" src="https://cloud.githubusercontent.com/assets/14365994/22677574/37ed2366-ed26-11e6-8333-06e197195c7f.png">

**Comment by popodidi** [comment]
Thanks for the response. This is actually something that needs to be enhanced in the next version 🤦‍♂️

**Comment by popodidi** [comment]
duplicate with #3
