### ISSUE TITLE
do you have support for navigation bar

### ISSUE THREAD

**Issue by ghost** [popodidi/HTagView#8]
im currently using 
```
let topActionBarConstraint = NSLayoutConstraint(item: detailTextView, attribute: .top, relatedBy: .equal, toItem: self.topLayoutGuide, attribute: .bottom, multiplier: 1, constant: 16)
            topActionBarConstraint.isActive = true
```
for contents under the navigation bar. Im not sure if your pod is able to sold this issue or have a shorter way of doing it.

**Comment by popodidi** [comment]
I am not sure if I get you right. As I know, there should be no problem as you put the `HTagView` inside a `UINavigationController.view`, since it is just an `UIView` with self-sizing `intrinsicContentSize` on vertical direction. Please explain more if anything goes wrong when you use it.

**Comment by ghost** [comment]
Sorry about that was the was an accident post or you pod the question was meant for somebody else.
